gmscompat: Handle all exact alarm denials
java.lang.SecurityException: Caller com.google.android.gms needs to hold android.permission.SCHEDULE_EXACT_ALARM to set exact alarms.
	at android.os.Parcel.createExceptionOrNull(Parcel.java:2425)
	at android.os.Parcel.createException(Parcel.java:2409)
	at android.os.Parcel.readException(Parcel.java:2392)
	at android.os.Parcel.readException(Parcel.java:2334)
	at android.app.IAlarmManager$Stub$Proxy.set(IAlarmManager.java:359)
	at android.app.AlarmManager.setImpl(AlarmManager.java:948)
	at android.app.AlarmManager.setImpl(AlarmManager.java:908)
	at android.app.AlarmManager.set(AlarmManager.java:818)
	at usv.k(:com.google.android.gms@213314046@21.33.14 (150400-395723304):1)
	at usv.o(:com.google.android.gms@213314046@21.33.14 (150400-395723304):0)
	at usv.e(:com.google.android.gms@213314046@21.33.14 (150400-395723304):2)
	at com.google.android.contextmanager.controller.EventHandler$AlarmSetter.c(:com.google.android.gms@213314046@21.33.14 (150400-395723304):8)
	at exr.d(:com.google.android.gms@213314046@21.33.14 (150400-395723304):3)
	at ext.l(:com.google.android.gms@213314046@21.33.14 (150400-395723304):0)
	at evr.a(:com.google.android.gms@213314046@21.33.14 (150400-395723304):143)
	at ext.run(:com.google.android.gms@213314046@21.33.14 (150400-395723304):2)
	at exp.handleMessage(:com.google.android.gms@213314046@21.33.14 (150400-395723304):3)
	at uwe.run(:com.google.android.gms@213314046@21.33.14 (150400-395723304):2)
	at uwo.c(:com.google.android.gms@213314046@21.33.14 (150400-395723304):6)
	at uwo.run(:com.google.android.gms@213314046@21.33.14 (150400-395723304):8)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at vcm.run(:com.google.android.gms@213314046@21.33.14 (150400-395723304):0)
	at java.lang.Thread.run(Thread.java:920)

Change-Id: I6a179661a3da33cba54cbc07c48adcebcaf008a8
Signed-off-by: Dmitrii <bankersenator@gmail.com>